### ISSUE TITLE
in readme dotnet version was 5.0.410 but release binary was 2.0

### ISSUE THREAD

**Issue by pp0236** [YumeGod/IronBrew2-Modify#1]

**Comment by YumeGod** [comment]
Try to execute the release binary file using dotnet 5.0.410, I'm not sure what happened.

**Comment by pp0236** [comment]
> Try to execute the release binary file using dotnet 5.0.410, I'm not sure what happened.

in project settings dotnet version was set to netcoreapp2.0

**Comment by YumeGod** [comment]
> > Try to execute the release binary file using dotnet 5.0.410, I'm not sure what happened.
> 
> in project settings dotnet version was set to netcoreapp2.0

Will correct dotnet version in the next commit
